"use client";

import { useState, useEffect } from "react";
import { supabaseBrowser } from "@/lib/supabase-browser";
import { useUIStore } from "@/store/useUIStore";
import { useProfile as useNewProfile } from "@/hooks/useProfile";
import { useProfile } from "@/contexts/ProfileContext";
import { useTour } from "@/contexts/TourContext";

const DEBUG_MODAL = false; // Set to true for detailed logs
const debugModal = (message: string, data?: any) => {
  if (DEBUG_MODAL) console.log(message, data);
};

// Helper: Check if name is a "real" user-entered name (not auto-generated from email/defaults)
const isRealName = (name: string | null | undefined, email?: string | null): boolean => {
  if (!name || name.trim() === '') return false;
  const trimmedName = name.trim().toLowerCase();
  // Check against known auto-generated defaults
  const autoGeneratedDefaults = ['alien', 'heartverse wanderer', 'wanderer'];
  if (autoGeneratedDefaults.includes(trimmedName)) return false;
  // Check if name is just the email prefix (before @)
  if (email) {
    const emailPrefix = email.split('@')[0]?.toLowerCase();
    if (trimmedName === emailPrefix) return false;
  }
  return true;
};

export default function WhatShouldWeCallYouModal() {
  // Hooks (fixed order; all at top)
  const { showNamePrompt, namePromptFromAuth, closeNamePrompt, openElementSelection } = useUIStore();

  const { updateProfileName, updateProfile, profile } = useProfile();
  const { completeOnboarding, refreshProfile } = useNewProfile();
  const { start: startTour } = useTour();
  const [name, setName] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [currentUser, setCurrentUser] = useState<any>(null);
  const [authChecked, setAuthChecked] = useState(false);
  const [shouldStartTourAfterEnter, setShouldStartTourAfterEnter] = useState(false);
  const [mounted, setMounted] = useState(false);

  // Phase state: 'warp' shows animation, 'name' shows name input
  const [phase, setPhase] = useState<'warp' | 'name'>('warp');

  // Prevent hydration mismatch
  useEffect(() => {
    setMounted(true);
  }, []);

  // Reset phase when modal opens
  useEffect(() => {
    if (showNamePrompt) {
      setPhase('warp');
    }
  }, [showNamePrompt]);

  // Auto-transition from warp to name after animation
  useEffect(() => {
    if (showNamePrompt && phase === 'warp' && mounted) {
      const timer = setTimeout(() => {
        setPhase('name');
      }, 2500); // 2.5 second warp animation
      return () => clearTimeout(timer);
    }
  }, [showNamePrompt, phase, mounted]);

  // Debug modal state changes
  useEffect(() => {
    debugModal('🎭 WhatShouldWeCallYouModal state:', { 
      showNamePrompt, 
      namePromptFromAuth, 
      mounted, 
      authChecked 
    });
  }, [showNamePrompt, namePromptFromAuth, mounted, authChecked]);


  // Check authentication and prefill name when modal opens
  // Uses getSession() to avoid AuthSessionMissingError when logged out
  useEffect(() => {
    const checkAuth = async () => {
      try {
        // Use getSession() first - does NOT throw when logged out
        const { data: { session } } = await supabaseBrowser.auth.getSession();
        // If no session, user is null - this is expected for logged-out users
        setCurrentUser(session?.user || null);
      } finally {
        setAuthChecked(true);
      }
    };

    if (showNamePrompt) {
      checkAuth();
      // Prefill with current profile name ONLY if it's a real user-entered name
      // Don't prefill auto-generated names (email prefix, "alien", etc.)
      if (profile?.name && isRealName(profile.name, profile.email)) {
        setName(profile.name);
      } else {
        setName(''); // Clear any auto-generated name
      }
    }
  }, [showNamePrompt, profile?.name, profile?.email]);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!name.trim()) return;
    
    setLoading(true);
    setError(null);
    
    try {
      // Validate that name is not empty
      const trimmedName = name.trim();
      if (!trimmedName) {
        setError("Please enter a name");
        return;
      }

      // Play join-alien.mp3 sound
      const audio = new Audio('/audio/join-alien.mp3');
      audio.play().catch(e => debugModal('Audio play failed:', e));
      
      // Save the name but don't complete onboarding yet - still need element selection
      await updateProfileName(trimmedName);
      // Refresh profile to ensure UI updates
      await refreshProfile();
      
      // Force profile refresh in other components
      try {
        window.dispatchEvent(new CustomEvent('auth:profile-updated'));
      } catch {}
      
      // Close name prompt and open element selection
      closeNamePrompt();
      openElementSelection();
    } catch (e: any) {
      setError(e?.message || "Failed to save name");
    } finally {
      setLoading(false);
    }
  }

  // Enter the Heartverse click: close this modal and open element selection
  const handleEnterHeartverse = () => {
    // Transition to element selection
    closeNamePrompt();
    openElementSelection();
    // Defer tour until after profile is complete (name + element)
    const hasSeenTour = !!profile?.has_seen_tour;
    if (!hasSeenTour) {
      setShouldStartTourAfterEnter(true);
    }
  };

  // Guard-close in an effect to avoid updating state during render
  // However, if the user just came from auth callback with completeProfile=1,
  // we should NOT auto-close even if they have a name (they may want to update it)
  useEffect(() => {
    if (!showNamePrompt) return;
    if (!authChecked) return;
    
    // If this modal was opened from auth callback (namePromptFromAuth=true),
    // never auto-close it - let the user explicitly interact with it
    if (namePromptFromAuth) {
      debugModal('🔒 Modal opened from auth - preventing auto-close');
      return;
    }
    
    // Add a small delay to prevent rapid state changes from auto-closing
    // the modal before the user sees it
    const timeoutId = setTimeout(() => {
      // Only auto-close if we have a user with a REAL user-entered name AND
      // this wasn't triggered by the explicit auth callback flow AND
      // modal is still open (to prevent stale closures)
      // Note: Auto-generated names (email prefix, "alien", etc.) should NOT trigger auto-close
      const hasRealName = isRealName(profile?.name, profile?.email);
      if (showNamePrompt && !namePromptFromAuth && currentUser && profile && hasRealName) {
        debugModal('🚪 Auto-closing name prompt - user already has real name');
        closeNamePrompt();
      }
    }, 200);

    return () => clearTimeout(timeoutId);
  }, [showNamePrompt, authChecked, currentUser, profile, namePromptFromAuth, closeNamePrompt]);

  // Safely start tour once user clicks Enter and profile is complete
  useEffect(() => {
    if (!shouldStartTourAfterEnter) return;
    // Require both name and element before starting the tour
    if (!profile?.name || !profile?.element) return;
    // Start the tour and mark as seen
    try { startTour(); } catch {}
    try { updateProfile({ has_seen_tour: true, profile_complete: true }); } catch {}
    setShouldStartTourAfterEnter(false);
  }, [shouldStartTourAfterEnter, profile?.name, profile?.element, startTour, updateProfile]);

  // Early returns come after all hooks
  if (!mounted) {
    debugModal('🚫 Modal not rendering: not mounted');
    return null;
  }
  if (!showNamePrompt) {
    debugModal('🚫 Modal not rendering: showNamePrompt=false');
    return null;
  }
  if (typeof document === 'undefined') {
    debugModal('🚫 Modal not rendering: document undefined');
    return null;
  }

  debugModal('✅ Rendering WhatShouldWeCallYouModal', { 
    showNamePrompt, 
    namePromptFromAuth, 
    mounted,
    authChecked,
    currentUser: !!currentUser,
    profile: !!profile,
    profileName: profile?.name
  });

  // Chrome-compatible rendering: render directly instead of portal for better compatibility
  // Force visibility with inline styles for Chrome
  const forceVisible = showNamePrompt && mounted;
  
  debugModal('🎨 Modal visibility state:', { showNamePrompt, mounted, forceVisible });
  
  return (
    <>
      {/* Hologram base glow - align within profile bar/light beam bounds */}
      <div
        className="fixed flex justify-center"
        style={{
          zIndex: 9999999,
          pointerEvents: 'none',
          left: 0,
          right: 0,
          top: 'var(--profile-bar-boundary, 64px)',
          bottom: 'calc(var(--light-beam-boundary, 120px) + var(--beam-height, 0px))',
          alignItems: 'flex-start',
          paddingTop: '200px'
        }}
      >
        <div
          style={{
            width: 'min(120vw, 700px)',
            height: '200px',
            background: 'radial-gradient(ellipse 80% 100% at 50% 0%, rgba(0,255,255,0.7) 0%, rgba(0,255,255,0.4) 30%, rgba(0,255,255,0.1) 60%, transparent 100%)',
            filter: 'blur(100px)'
          }}
        />
      </div>

      {/* Onboarding Modal - same position as welcome home display */}
      <div
        className="fixed flex justify-center pointer-events-none"
        style={{
          zIndex: 9999999,
          left: 0,
          right: 0,
          top: 'var(--profile-bar-boundary, 64px)',
          bottom: 'calc(var(--light-beam-boundary, 120px) + var(--beam-height, 0px))',
          alignItems: 'flex-start'
        }}
      >
        <div
          className="onboarding-hologram-container pointer-events-auto"
          style={{
            width: 'min(92vw, 500px)',
            height: '100%',
            padding: '16px 24px 20px 24px',
            borderRadius: 18,
            background: 'rgba(0,0,0,0.6)',
            border: '1px solid rgba(0,255,255,0.55)',
            boxShadow: '0 -8px 25px rgba(0,255,255,0.4), 0 -4px 15px rgba(0,255,255,0.25), 0 12px 30px rgba(0,0,0,0.4), 0 0 24px rgba(0,255,255,0.45)',
            backdropFilter: 'blur(12px) saturate(140%)',
            color: '#00FFFF',
            position: 'relative',
            display: 'flex',
            flexDirection: 'column'
          }}
        >
        
        {/* Close button - blue X in circle */}
        <button
          onClick={closeNamePrompt}
          className="absolute top-4 right-4 w-8 h-8 rounded-full flex items-center justify-center transition-all duration-200 hover:scale-110"
          style={{
            background: 'rgba(0,255,255,0.2)',
            border: '1px solid rgba(0,255,255,0.6)',
            color: '#00FFFF',
            boxShadow: '0 0 10px rgba(0,255,255,0.3)',
            fontSize: '14px',
            fontWeight: 'bold'
          }}
        >
          ×
        </button>
        
        {/* Soft bottom glow pseudo element */}
        <div 
          className="absolute"
          style={{
            bottom: '-15px',
            left: '50%',
            transform: 'translateX(-50%)',
            width: '120%',
            height: '30px',
            background: 'radial-gradient(ellipse 60% 100% at 50% 0%, rgba(0,255,255,0.6) 0%, rgba(0,255,255,0.3) 40%, transparent 80%)',
            filter: 'blur(30px)',
            pointerEvents: 'none',
            zIndex: -1
          }}
        />
        
        {/* Top bloom glow */}
        <div 
          className="absolute"
          style={{
            top: '-10px',
            left: '50%',
            transform: 'translateX(-50%)',
            width: '80%',
            height: '20px',
            background: 'radial-gradient(ellipse 70% 100% at 50% 100%, rgba(0,255,255,0.4) 0%, rgba(0,255,255,0.2) 50%, transparent 100%)',
            filter: 'blur(25px)',
            pointerEvents: 'none',
            zIndex: -1
          }}
        />

        {/* Warp Animation Styles */}
        <style>{`
          @keyframes warpPulse {
            0%, 100% { transform: scale(1); opacity: 0.8; }
            50% { transform: scale(1.1); opacity: 1; }
          }
          @keyframes warpGlow {
            0%, 100% { filter: blur(0px); text-shadow: 0 0 20px rgba(0,255,255,0.8), 0 0 40px rgba(0,255,255,0.6), 0 0 60px rgba(0,255,255,0.4); }
            50% { filter: blur(1px); text-shadow: 0 0 30px rgba(0,255,255,1), 0 0 60px rgba(0,255,255,0.8), 0 0 90px rgba(0,255,255,0.6); }
          }
          @keyframes warpLines {
            0% { transform: translateY(100%) scaleY(0); opacity: 0; }
            50% { transform: translateY(0%) scaleY(1); opacity: 1; }
            100% { transform: translateY(-100%) scaleY(0); opacity: 0; }
          }
          @keyframes fadeIn {
            from { opacity: 0; transform: translateY(10px); }
            to { opacity: 1; transform: translateY(0); }
          }
          .warp-text {
            animation: warpGlow 1s ease-in-out infinite;
          }
          .warp-container {
            animation: warpPulse 2s ease-in-out infinite;
          }
          .name-form-enter {
            animation: fadeIn 0.5s ease-out forwards;
          }
        `}</style>

        {phase === 'warp' ? (
          /* WARP PHASE - Animation */
          <div className="warp-container flex flex-col items-center justify-center flex-1">
            {/* Warp speed lines */}
            <div className="absolute inset-0 overflow-hidden pointer-events-none">
              {[...Array(8)].map((_, i) => (
                <div
                  key={i}
                  style={{
                    position: 'absolute',
                    left: `${10 + i * 12}%`,
                    top: 0,
                    width: '2px',
                    height: '100%',
                    background: 'linear-gradient(to bottom, transparent, rgba(0,255,255,0.6), transparent)',
                    animation: `warpLines 1.5s ease-in-out infinite`,
                    animationDelay: `${i * 0.15}s`
                  }}
                />
              ))}
            </div>

            {/* Main warp text */}
            <div
              className="warp-text text-center"
              style={{
                color: '#00FFFF',
                fontSize: '28px',
                fontWeight: 'bold',
                letterSpacing: '4px'
              }}
            >
              WARP TO HEARTVERSE
            </div>

            {/* Subtitle */}
            <div
              className="mt-4 text-center"
              style={{
                color: 'rgba(0,255,255,0.7)',
                fontSize: '14px',
                textShadow: '0 0 8px rgba(0,255,255,0.4)'
              }}
            >
              Initiating transport...
            </div>
          </div>
        ) : (
          /* NAME PHASE - Input Form */
          <div className="name-form-enter flex flex-col flex-1">
            {/* Header */}
            <div
              className="text-center mb-2"
              style={{
                color: '#00FFFF',
                textShadow: '0 0 8px rgba(0,255,255,0.6)',
                fontSize: '18px',
                fontWeight: 'bold'
              }}
            >
              Choose your Alien name
            </div>

            {/* Thin cyan neon line */}
            <div
              className="w-full h-px mb-4"
              style={{
                background: 'linear-gradient(90deg, transparent, rgba(0,255,255,0.8) 20%, rgba(0,255,255,1) 50%, rgba(0,255,255,0.8) 80%, transparent)',
                boxShadow: '0 0 4px rgba(0,255,255,0.6)'
              }}
            />

            {error && (
              <div className="relative mb-3 rounded-md bg-red-50/10 border border-red-200/40 p-2 text-sm text-red-200">
                {error}
              </div>
            )}

            <form onSubmit={handleSubmit} className="space-y-3">
              <input
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="Your name"
                required
                disabled={loading}
                className="block w-full rounded-md border px-3 py-3 text-sm shadow-sm focus:outline-none disabled:opacity-50"
                style={{
                  border: '1px solid rgba(0,255,255,0.4)',
                  background: 'rgba(0,0,0,0.3)',
                  color: '#00FFFF',
                  textShadow: '0 0 4px rgba(0,255,255,0.6)',
                  backdropFilter: 'blur(4px)',
                  fontSize: '16px'
                }}
                maxLength={50}
              />

              <button
                type="submit"
                disabled={loading || !name.trim()}
                className="w-full inline-flex items-center justify-center rounded-lg px-4 py-3 text-sm font-medium transition disabled:opacity-50"
                style={{
                  background: 'rgba(0,255,255,0.15)',
                  border: '1px solid rgba(0,255,255,0.5)',
                  color: '#00FFFF',
                  textShadow: '0 0 8px rgba(0,255,255,0.8), 0 0 16px rgba(0,255,255,0.6), 0 0 24px rgba(0,255,255,0.4)',
                  boxShadow: loading || !name.trim()
                    ? 'none'
                    : '0 0 15px rgba(0,255,255,0.4), 0 0 25px rgba(0,255,255,0.2)'
                }}
              >
                {loading ? "SAVING..." : "CONFIRM"}
              </button>
            </form>
          </div>
        )}
        </div>
      </div>
    </>
  );
}
