import { execSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';

function safeExec(cmd) {
  try {
    return execSync(cmd, { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  } catch {
    return 'unknown';
  }
}

const sha = safeExec('git rev-parse --short HEAD');
const branch = safeExec('git rev-parse --abbrev-ref HEAD');
const date = new Date().toISOString();
const env = process.env.NODE_ENV || 'development';

const outDir = resolve('lib');
mkdirSync(outDir, { recursive: true });

const ts = `// Auto-generated by scripts/writeBuildInfo.mjs\nexport const buildInfo = {\n  sha: '${sha}',\n  branch: '${branch}',\n  date: '${date}',\n  env: '${env}'\n} as const;\n`;

writeFileSync(resolve(outDir, 'buildInfo.ts'), ts);
console.log(`Wrote lib/buildInfo.ts => ${sha} @ ${date} (${env})`);

